apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist.backendFullname" . }}
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "todolist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        {{- include "todolist.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "todolist.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag }}"
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "todolist.backendFullname" . }}-config
          env:
            {{- if .Values.postgres.auth.existingSecret }}
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.existingSecret }}
                  key: {{ .Values.postgres.auth.existingSecretKeys.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.existingSecret }}
                  key: {{ .Values.postgres.auth.existingSecretKeys.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.existingSecret }}
                  key: {{ .Values.postgres.auth.existingSecretKeys.password }}
            - name: DATABASE_URL
              value: {{ printf "postgresql+psycopg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@%s:%v/$(POSTGRES_DB)" (include "todolist.postgresFullname" .) .Values.postgres.service.port | quote }}
            {{- else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "todolist.backendFullname" . }}-secret
                  key: DATABASE_URL
            {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
