{{- if and .Values.secrets.create (or .Values.externalPostgres.enabled (not .Values.postgres.auth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.backendFullname" . }}-secret
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.externalPostgres.enabled }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s:%v/%s" .Values.externalPostgres.auth.username .Values.externalPostgres.auth.password .Values.externalPostgres.host .Values.externalPostgres.port .Values.externalPostgres.auth.database | quote }}
  POSTGRES_HOST: {{ .Values.externalPostgres.host | quote }}
  POSTGRES_PORT: {{ .Values.externalPostgres.port | toString | quote }}
  POSTGRES_DB: {{ .Values.externalPostgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.externalPostgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.externalPostgres.auth.password | quote }}
  POSTGRES_BOOTSTRAP_DB: {{ .Values.externalPostgres.bootstrapDatabase | quote }}
  {{- else }}
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s:%v/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "todolist.postgresFullname" .) .Values.postgres.service.port .Values.postgres.auth.database | quote }}
  POSTGRES_HOST: {{ include "todolist.postgresFullname" . | quote }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | toString | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_BOOTSTRAP_DB: {{ .Values.postgres.auth.database | quote }}
  {{- end }}
{{- end }}
