apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist.backendFullname" . }}-config
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.backend.corsOrigins | toJson | quote }}
  OIDC_CLIENT_ID: {{ .Values.auth.clientId | quote }}
  OIDC_ISSUER_URL: {{ .Values.auth.issuerUrl | quote }}
  OIDC_JWKS_URL: {{ .Values.auth.jwksUrl | quote }}
