{{- if and .Values.secrets.create (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.backendFullname" . }}-secret
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s:%v/%s" .Values.postgres.auth.username .Values.postgres.auth.password (include "todolist.postgresFullname" .) .Values.postgres.service.port .Values.postgres.auth.database | quote }}
{{- end }}
