apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist.frontendFullname" . }}-config
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.frontend.runtimeConfig.apiUrl | quote }}
  VITE_AUTH_AUTHORITY: {{ .Values.auth.authorityUrl | quote }}
  VITE_AUTH_CLIENT_ID: {{ .Values.auth.clientId | quote }}
  VITE_AUTH_REDIRECT_URI: {{ .Values.auth.redirectUri | quote }}
  VITE_AUTH_POST_LOGOUT_REDIRECT_URI: {{ .Values.auth.postLogoutRedirectUri | quote }}
