apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todolist.frontendFullname" . }}
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      {{- include "todolist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        {{- include "todolist.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "todolist.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "todolist.frontendFullname" . }}-config
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

