{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.keycloakFullname" . }}
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: keycloak
    {{- include "todolist.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
{{- end }}

