{{- if and .Values.keycloak.enabled .Values.secrets.create (not .Values.keycloak.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todolist.keycloakFullname" . }}-secret
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.user | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
{{- end }}

