{{- if and .Values.keycloak.enabled .Values.keycloak.realmImport.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todolist.keycloakFullname" . }}-realm
  namespace: {{ include "todolist.namespace" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
data:
  realm-export.json: |
{{ .Values.keycloak.realmImport.json | indent 4 }}
{{- end }}

