---
namespaceOverride: ''
nameOverride: ''
fullnameOverride: ''
images:
  backend:
    repository: ghcr.io/pascariucosmin93/todo-backend
    tag: 0.0.5
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/pascariucosmin93/todo-frontend
    tag: 0.0.5
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
imagePullSecrets: []
serviceAccount:
  create: false
  name: ''
backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
  corsOrigins:
  - https://todo.local
  resources: {}
frontend:
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
    annotations: {}
    loadBalancerIP: ''
    externalTrafficPolicy: Cluster
  runtimeConfig:
    apiUrl: https://api.todo.local/api/v1
  resources: {}
auth:
  authorityUrl: https://auth.todo.local/application/o/todo-app/
  issuerUrl: https://auth.todo.local/application/o/todo-app/
  jwksUrl: https://auth.todo.local/application/o/todo-app/jwks/
  clientId: todo-frontend
  redirectUri: https://todo.local/
  postLogoutRedirectUri: https://todo.local/
postgres:
  enabled: true
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ''
  auth:
    database: todolist
    username: cosmin
    password: minimouse
    existingSecret: ''
    existingSecretKeys:
      database: POSTGRES_DB
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
  resources: {}
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    frontend: todo.local
    backend: api.todo.local
  tls: []
secrets:
  create: true
