---
namespaceOverride: ''
nameOverride: ''
fullnameOverride: ''
images:
  backend:
    repository: ghcr.io/pascariucosmin93/todo-backend
    tag: 1.0.0
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/pascariucosmin93/todo-frontend
    tag: 1.0.0
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
imagePullSecrets: []
serviceAccount:
  create: false
  name: ''
backend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000
  corsOrigins:
  - https://todo.example.internal
  runtimeSecret:
    existingSecret: todo-todolist-runtime
  resources: {}
frontend:
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
    annotations: {}
    loadBalancerIP: ''
    externalTrafficPolicy: Cluster
  runtimeConfig:
    apiUrl: "/api/v1"
    backendUpstreamUrl: http://todo-todolist-backend:8000
  resources: {}
externalPostgres:
  enabled: true
  host: postgres.postgress.svc.cluster.local
  port: 5432
  bootstrapDatabase: forgejo2
  auth:
    database: todolist
    username: ''
    password: ''
appAuth:
  username: ''
  password: ''
  sessionToken: ''
postgres:
  enabled: false
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ''
  auth:
    database: todolist
    username: cosmin
    password: minimouse
    existingSecret: ''
    existingSecretKeys:
      database: POSTGRES_DB
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
  resources: {}
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    frontend: todo.local
    backend: api.todo.local
  tls: []
secrets:
  create: true
