images:
  backend:
    repository: ghcr.io/pascariucosmin93/todo-backend
    tag: "0.0.1"
  frontend:
    repository: ghcr.io/pascariucosmin93/todo-frontend
    tag: "0.0.1"

backend:
  corsOrigins:
    - "https://todo.example.internal"

frontend:
  service:
    type: LoadBalancer
    annotations: {}
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
  runtimeConfig:
    apiUrl: "https://api.todo.example.internal/api/v1"
auth:
  authorityUrl: "https://auth.todo.example.internal/application/o/todo-app/"
  issuerUrl: "https://auth.todo.example.internal/application/o/todo-app/"
  jwksUrl: "https://auth.todo.example.internal/application/o/todo-app/jwks/"
  clientId: "todo-frontend"
  redirectUri: "https://todo.example.internal/"
  postLogoutRedirectUri: "https://todo.example.internal/"

ingress:
  enabled: true
  className: nginx
  hosts:
    frontend: todo.example.internal
    backend: api.todo.example.internal

postgres:
  auth:
    existingSecret: "todolist-postgres"
