---
namespaceOverride: ''
nameOverride: ''
fullnameOverride: ''
images:
  backend:
    repository: ghcr.io/pascariucosmin93/todo-backend
    tag: 0.0.5
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/pascariucosmin93/todo-frontend
    tag: 0.0.5
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
imagePullSecrets: []
serviceAccount:
  create: false
  name: ''
backend:
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 8000
  corsOrigins:
  - http://10.13.13.101:8097
  resources: {}
frontend:
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
    annotations: {}
    loadBalancerIP: ''
    externalTrafficPolicy: Cluster
  runtimeConfig:
    apiUrl: http://10.13.13.101:8100/api/v1
  resources: {}
auth:
  authorityUrl: http://10.13.13.101:8098/application/o/todo-app/
  issuerUrl: http://10.13.13.101:8098/application/o/todo-app/
  jwksUrl: http://10.13.13.101:8098/application/o/todo-app/jwks/
  clientId: todo-frontend
  redirectUri: http://10.13.13.101:8097/
  postLogoutRedirectUri: http://10.13.13.101:8097/
postgres:
  enabled: true
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
    storageClass: ''
  auth:
    database: todolist
    username: cosmin
    password: minimouse
    existingSecret: ''
    existingSecretKeys:
      database: POSTGRES_DB
      username: POSTGRES_USER
      password: POSTGRES_PASSWORD
  resources: {}
ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    frontend: todo.local
    backend: api.todo.local
  tls: []
secrets:
  create: true
