images:
  backend:
    repository: ghcr.io/pascariucosmin93/todo-backend
    tag: "0.0.1"
  frontend:
    repository: ghcr.io/pascariucosmin93/todo-frontend
    tag: "0.0.1"

backend:
  corsOrigins:
    - "https://todo.example.internal"

frontend:
  service:
    type: LoadBalancer
    annotations: {}
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
  runtimeConfig:
    apiUrl: "/api/v1"
    backendUpstreamUrl: "http://todo-todolist-backend:8000"

externalPostgres:
  enabled: true
  host: "postgres.postgress.svc.cluster.local"
  port: 5432
  bootstrapDatabase: "forgejo2"
  auth:
    database: "todolist"
    username: "devops"
    password: "devops"

ingress:
  enabled: true
  className: nginx
  hosts:
    frontend: todo.example.internal
    backend: api.todo.example.internal

postgres:
  enabled: false
  auth:
    existingSecret: "todolist-postgres"
